# Google Advanced Data ANalytics specialization 2

## matplotlib
A library for creating static, animated, and interactive visualizations in Python 

## Seaborn:
A visualization library based on matplotlib that provides a simppler interface for working with common plots and graphs

## NumPy:
An essential library that contains multidimensional array and matrix data structures and functions to manipulate them.

## pandas:
A powerful library build on top of NumPy that's used to manipulate and analyze tabular data 

**Module**:
A simple Python file containing a collection of functions and global variables

**Global Variable**
Variables that can be accessed from anywhere in a program or script

## Introduction to Numpy
### Vectorization:
- Enables operations to be performed on multiple components of a data object at the same time.


In [ ]:
list_a = [1, 2, 3]
list_b = [2, 4, 6]

# using numpy for numerical operations
import numpy as np
array_a = np.array(list_a)
array_b = np.array(list_b)

array_a * array_b

array([ 2,  8, 18])

### Commonly used built in modules
1. `datetime`
provides many helpful date and time conversions and calculations 

In [6]:
import datetime 
date = datetime.date(1977, 5, 8)
print(date)
print(date.year)

delta = datetime.timedelta(days=30)
print(date - delta)

1977-05-08
1977
1977-04-08


2. `math` provides access to mathmatical functions

In [7]:
import math 
print(math.exp(0))
print(math.log(1))
print(math.factorial(4))
print(math.sqrt(100))

1.0
0.0
24
10.0


3. `random` Useful for generating pseudo-random numbers

In [8]:
import random 
print(random.random())
print(random.choice([1, 2, 3]))
print(random.randint(1, 10))

0.42549589006098254
1
8


In [9]:
import numpy as np 
import pandas as pd 
print(np.__version__)
print(pd.__version__)

1.26.4
2.2.3


### N-dimensional array (ndarray)
The core data object of NumPy
- they are mutable
- to change a size on an array you have to reassign it 
- all the elements of an array should be of same data type
- np arrrays can be multidimentional 

In [10]:
import numpy as np 

x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [12]:
x[-1] = 5
x

array([1, 2, 3, 5])

In [14]:
arr = np.array([1, 2, 'cpcpnut'])
arr

array(['1', '2', 'cpcpnut'], dtype='<U21')

>`dtype`:
A NumPy attribute used to check the data type of the contents of an array 

In [15]:
arr.dtype

dtype('<U21')

> `shape`: A NumPy attribute used to check the shape of an array 

In [16]:
arr.shape

(3,)

>`ndim`: A NumPy attribute used to check the number of dimensions of an array.

In [17]:
arr.ndim

1

In [ ]:
# A 2 dimensional array is a lists of lists
arr_2d = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(arr_2d.shape)
print(arr_2d.ndim)
arr_2d

(4, 2)
2


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
arr_2d = arr_2d.reshape(2, 4)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
# A 3 dimensional array is a lists of lists of list
arr_3d = np.array([[[1, 2, 3],
                    [3, 4, 5]],
                   
                   [[5, 6, 7],
                    [7, 8, 9]]])

print(arr_3d.shape)
print(arr_3d.ndim)
arr_3d

(2, 2, 3)
3


array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [21]:
# calculating mean 
arr = np.array([1, 2, 3, 4, 5])
np.mean(arr)

3.0

In [22]:
# calculating log
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [23]:
np.ceil(5.3)

6.0

>`np.array()`: This creates an `ndarray`. THere is no limit to how many dimensions a NumPy array can have, but arrays with many dimensions can be more difficult to work with 

In [25]:
# 1d array:
import numpy as np 
array_1d = np.array([1, 2, 3])
array_1d

array([1, 2, 3])

In [27]:
# 2d array:
array_2d = np.array([[1, 2, 3], 
                    [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

> `np.zeros()`: This creates an array of a designated shape that is pre-filled with zeros:

In [28]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

> `np.ones()`: This creates an array of a designated shape that is pre-filled with ones:

In [29]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

>`np.full()`: This creates an array of a designated shape that is pre-filled with a specified value

In [30]:
np.full((5, 3), 8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

### Array Methods:
- NumPy arrays have many methods that allow you to manipulate and operate on them. 

>`ndarray.flatten()`:
This returns a copy of the array collapsed into one dimension

In [31]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.flatten()

[[1 2 3]
 [4 5 6]]



array([1, 2, 3, 4, 5, 6])

>`nd_array.reshape()`: This gives a new shape to an array without changing its data. 

In [34]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.reshape(3, 2)

[[1 2 3]
 [4 5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

## Introduction to Pandas
### Tabular data 
- Data that is in the form of a table, with rows and columns

In [2]:
import numpy as np 
import pandas as pd
dataframe = pd.read_csv('~/Desktop/data_analysis/DATA/raw_data/train.csv')
print(dataframe.head(20))

    PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.

In [ ]:
# finding mean 
dataframe['Age'].mean()

29.69911764705882

In [4]:
# finding max
dataframe['Age'].max()

80.0

In [5]:
#  finding min
dataframe['Age'].min()

0.42

### Standard Deviation 
is a measure of spread 
- low sd means the data is closely clustered around the mean/average
- high sd means the data is widely clustered away from the mean/average

In [6]:
# finding standard deviation 
dataframe['Age'].std()

14.526497332334044

In [7]:
# checking how many passengers were in each class
dataframe['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [8]:
# checking summary statistics
dataframe.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
#filtering based on simple condition
# only selecting 3rd class passengers who were older than 60
dataframe[(dataframe['Age'] > 60) & (dataframe['Pclass'] == 3)]

PassengerId  Survived  Pclass                       Name     Sex   Age  \
116          117         0       3       Connors, Mr. Patrick    male  70.5   
280          281         0       3           Duane, Mr. Frank    male  65.0   
326          327         0       3  Nysveen, Mr. Johan Hansen    male  61.0   
483          484         1       3     Turkula, Mrs. (Hedwig)  female  63.0   
851          852         0       3        Svensson, Mr. Johan    male  74.0   

     SibSp  Parch  Ticket    Fare Cabin Embarked  
116      0      0  370369  7.7500   NaN        Q  
280      0      0  336439  7.7500   NaN        Q  
326      0      0  345364  6.2375   NaN        S  
483      0      0    4134  9.5875   NaN        S  
851      0      0  347060  7.7750   NaN        S

In [10]:
# Manipulating and changing the data 
# adding a column that represents the inflation adjusted fare of ticket from 1912 to 2023
dataframe['2023_Fare'] = dataframe['Fare'] * 146.14
dataframe

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked     2023_Fare  
0        0         A/5 21171   7.2500   NaN        S   1059.515000  
1        0          PC 17599  71.2833   C85        C  10417.341462  
2        0  STON/O2. 3101282   7.9250   NaN        S   1158.159500  
3        0            113803  53.1000  C123        S   7760.034000  
4        0            373450   8.0500   NaN        S   1176.427000  
..     ...               ...      ...   ...      ...           ...  
886      0            211536  13.0000   NaN        S   1899.820000  
887      0            112053  30.0000   B42        S   4384.200000  
888      2        W./C. 6607  23.4500   NaN        S   3426.983000  
889      0            111369  30.0000  C148        C   4384.200000  
890      0            370376   7.7500   NaN        Q   1132.585000  

[891 rows x 13 columns]

In [ ]:
# accessing rows using indexing 
dataframe.iloc[3]

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
2023_Fare                                          7760.034
Name: 3, dtype: object

In [18]:
# data groupings and aggrigations
fare = dataframe.groupby(['Sex', 'Pclass']).agg({'Fare': ['count', 'sum']})
fare['fare_avg'] = fare['Fare']['sum'] / fare['Fare']['count']
fare


Fare               fare_avg
              count        sum            
Sex    Pclass                             
female 1         94  9975.8250  106.125798
       2         76  1669.7292   21.970121
       3        144  2321.1086   16.118810
male   1        122  8201.5875   67.226127
       2        108  2132.1125   19.741782
       3        347  4393.5865   12.661633

### Core pandas object classes
- DataFrame
- Series

#### DataFrame:
A two-dimensional, labeled data structure with rows and columns



In [ ]:
# Importing pandas and creating a DataFrame
import pandas as pd 

data = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=data)
df

col1  col2
0     1     3
1     2     4

In [21]:
import numpy as np 
# Creating a DataFrame with numpy arrays
df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c'], index=['x', 'y', 'z'])
df2


a  b  c
x  1  2  3
y  4  5  6
z  7  8  9

In [22]:
df3 = pd.read_csv('~/Desktop/data_analysis/DATA/raw_data/train.csv')
df3.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

#### Series:
- A one dimensional , labeled array
- most often use to represent individual rows or columns of a dataframe


In [24]:
# Print class of 1st row
print(type(df3.iloc[0]))
# Print class of 'Name' column
print(type(df3['Name']))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


In [25]:
titanic = pd.read_csv('~/Desktop/data_analysis/DATA/raw_data/train.csv')

In [26]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [27]:
titanic.shape

(891, 12)

In [28]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


> **NaN**: null values are represented in pandas as NaN which stands for "not a number"

In [29]:
titanic['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [30]:
titanic.Age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [31]:
titanic[['Name', 'Age']]

Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

> to select rows and columns by index use `iloc[]` A way to indicate in pandas that you want to select by integer-location-based position

In [ ]:
# for column
titanic.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [33]:
# for row
titanic.iloc[[0]]

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  
0      0  A/5 21171  7.25   NaN        S

In [ ]:
# multiple rows
titanic.iloc[0:8]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S

In [37]:
# selecting subset of rows and columns together
titanic.iloc[0:3, [3,4]]

Name     Sex
0                            Braund, Mr. Owen Harris    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                             Heikkinen, Miss. Laina  female

In [38]:
# single column entirely
titanic.iloc[:,[3]]

Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                       Graham, Miss. Margaret Edith
888           Johnston, Miss. Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

In [39]:
# single value in a pertcular row in a perticular column
titanic.iloc[0, 3]

'Braund, Mr. Owen Harris'

> `loc()` is similar to `iloc()` but it used to select padas rows and columns by name instead of index location

In [40]:
titanic.loc[1:3, ['Name']]

Name
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)

In [41]:
# adding new column to the dataframe 
titanic['Age_plus_100'] = titanic['Age'] + 100
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_plus_100  
0      0         A/5 21171   7.2500   NaN        S         122.0  
1      0          PC 17599  71.2833   C85        C         138.0  
2      0  STON/O2. 3101282   7.9250   NaN        S         126.0  
3      0            113803  53.1000  C123        S         135.0  
4      0            373450   8.0500   NaN        S         135.0

> - Attributes are characteristics of the object
> - Methods are actions or operations

#### Commonly used DataFrame attributes 

| Attribute | Description |
|-----------|-------------|
| columns   | Returns the column labels of the datafram |
| dtypes    | Returns the data types in the dataframe |
| iloc      | Accesses a group of rows and columns using integer-based indexing |
| loc       | Accesses a group of rows and columns by label(s) or a Boolean array |
| shape     | Returns a tuple representing the dimensionality of the dataframe |
| values    | Returns a NumPy representation of the dataframe |

#### Commonly used DataFrame methods:

| Method     | Description   |
|------------|---------------|
| apply()    | Applies a function over an axis of the dataframe |
| copy()     | Makes a copy of the dataframe's indices and data |
| describe() | returns descriptive statistics of the dataframe, including the minimum, max, mean, and percentile values of its numerice columns; the row countl and the data types |
| drop()     | Drops specified labels from rows or columns |
| groupby()  | Splits the dataframe, applies a function, and combines the results |
| head(n=5) | Returns the first n rows of the dataframe (default=5) |
| info()    | Returns a concise summary of the dataframe |
| isna()    | Returns a same sized Boolean dataframe indicating whether each value is null(can also use `isnull()` as an alias) |
| sort_values() | Sorts by the value across a given axis |


### Boolean Masking
A filtering technique that overlays a Boolean grid onto a dataframe in order to select only the values in the dataframe that align witht the True values of the grid

In [42]:
data = {'planet': ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune'],
        'radius_km': [2440, 6052, 6371, 3390, 69911, 58232, 25362, 24633],
        'moons': [0, 0, 1, 2, 80, 83, 27, 14]}
planets = pd.DataFrame(data)
planets

planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
4  Jupiter      69911     80
5   Saturn      58232     83
6   Uranus      25362     27
7  Neptune      24633     14

In [43]:
# Creating a boolean mask 
mask = planets['moons'] < 20
mask

0     True
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: moons, dtype: bool

In [44]:
planets[mask]

planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
7  Neptune      24633     14

In [45]:
planets[planets['moons'] < 20]

planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
7  Neptune      24633     14

In [46]:
moons_under_20 = planets[planets['moons'] < 20]
moons_under_20

planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
7  Neptune      24633     14

#### Operators used for the logic
| Operator | Logic |
|----------|-------|
|     `&`    | and   |
|         | or    |
|   `~`    | not  |

In [48]:
mask = (planets['moons'] < 10) | (planets['moons'] > 50)
mask

0     True
1     True
2     True
3     True
4     True
5     True
6    False
7    False
Name: moons, dtype: bool

In [50]:
planets[mask]

planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
4  Jupiter      69911     80
5   Saturn      58232     83

In [51]:
mask = (planets['moons']>20)& ~(planets['moons']==80) & ~(planets['radius_km']<50000)

In [53]:
planets[mask]

planet  radius_km  moons
5  Saturn      58232     83

### Grouping and aggregation 

`groupby()`:
A pandas DataFrame method that groups rows of the dataframe together based on their values at one or more columns, which allows further analysis of the groups

In [1]:
import numpy as np 
import pandas as pd 

solar_system = {'planet': ['Mercury', 'Venus',     'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune'],
        'radius_km': [2440, 6052, 6371, 3390, 69911, 58232, 25362, 24633],
        'moons': [0, 0, 1, 2, 80, 83, 27, 14], 
        'type': ['terrestrial', 'terrestrial', 'terrestrial', 'terrestrial', 'gas giant', 'gas giant', 'ice giant', 'ice giant'],
        'rings': ['no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'yes'],
        'mean_temp_c': [167, 464, 15, -65, -110, -140, -195, -214],
        'magnetic_field': ['yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'no']
        }
planets = pd.DataFrame(solar_system)
planets

planet  radius_km  moons         type rings  mean_temp_c magnetic_field
0  Mercury       2440      0  terrestrial    no          167            yes
1    Venus       6052      0  terrestrial    no          464             no
2    Earth       6371      1  terrestrial    no           15            yes
3     Mars       3390      2  terrestrial    no          -65             no
4  Jupiter      69911     80    gas giant   yes         -110            yes
5   Saturn      58232     83    gas giant   yes         -140            yes
6   Uranus      25362     27    ice giant   yes         -195            yes
7  Neptune      24633     14    ice giant   yes         -214             no

In [2]:
planets.groupby(['type'])


In [3]:
planets.groupby(['type']).sum()

planet  radius_km  moons     rings  mean_temp_c  \
type                                                                          
gas giant            JupiterSaturn     128143    163    yesyes         -250   
ice giant            UranusNeptune      49995     41    yesyes         -409   
terrestrial  MercuryVenusEarthMars      18253      3  nononono          581   

            magnetic_field  
type                        
gas giant           yesyes  
ice giant            yesno  
terrestrial     yesnoyesno

In [4]:
planets.groupby(['type']).sum()[['moons']]

moons
type              
gas giant      163
ice giant       41
terrestrial      3

In [7]:
planets.groupby(['type','magnetic_field']).mean(numeric_only=True)

radius_km  moons  mean_temp_c
type        magnetic_field                               
gas giant   yes               64071.5   81.5       -125.0
ice giant   no                24633.0   14.0       -214.0
            yes               25362.0   27.0       -195.0
terrestrial no                 4721.0    1.0        199.5
            yes                4405.5    0.5         91.0

`agg()`: Ahort for aggregate. A pandas groupby method that allows you to apply multiple calculations to groups of data

In [11]:
numeric_cols = planets.select_dtypes(include=[np.number]).columns
planets.groupby(['type'])[numeric_cols].agg(['mean', 'median'])




radius_km           moons        mean_temp_c       
                 mean   median   mean median        mean median
type                                                           
gas giant    64071.50  64071.5  81.50   81.5     -125.00 -125.0
ice giant    24997.50  24997.5  20.50   20.5     -204.50 -204.5
terrestrial   4563.25   4721.0   0.75    0.5      145.25   91.0

In [12]:
planets.groupby(['type', 'magnetic_field'])[numeric_cols].agg(['mean', 'max'])

radius_km        moons     mean_temp_c     
                                mean    max  mean max        mean  max
type        magnetic_field                                            
gas giant   yes              64071.5  69911  81.5  83      -125.0 -110
ice giant   no               24633.0  24633  14.0  14      -214.0 -214
            yes              25362.0  25362  27.0  27      -195.0 -195
terrestrial no                4721.0   6052   1.0   2       199.5  464
            yes               4405.5   6371   0.5   1        91.0  167

In [ ]:
# calculating 90th percentile of eah group 
def percentile_90(x):
    return x.quantile(0.9)


In [16]:
planets.groupby(['type', 'magnetic_field'])[numeric_cols].agg('mean', percentile_90)

radius_km  moons  mean_temp_c
type        magnetic_field                               
gas giant   yes               64071.5   81.5       -125.0
ice giant   no                24633.0   14.0       -214.0
            yes               25362.0   27.0       -195.0
terrestrial no                 4721.0    1.0        199.5
            yes                4405.5    0.5         91.0

### Merging and Joining data 

#### `concat()`
A pandas function that combines data either by adding it horizontally as new columns for existing rows, or vertically as new rows for existing columns

In [17]:
data = {'planet': ['Mercury', 'Venus', 'Earth', 'Mars', ],
        'radius_km': [2440, 6052, 6371, 3390],
        'moons': [0, 0, 1, 2]}
df1 = pd.DataFrame(data)
df1

planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2

In [21]:
data1 = {'planet': ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
        'radius_km': [69911, 58232, 25362, 24633],
        'moons': [80, 83, 27, 14]}
df2 = pd.DataFrame(data1)
df2

planet  radius_km  moons
0  Jupiter      69911     80
1   Saturn      58232     83
2   Uranus      25362     27
3  Neptune      24633     14

In [23]:
df3 = pd.concat([df1, df2], axis=0)
df3

planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
0  Jupiter      69911     80
1   Saturn      58232     83
2   Uranus      25362     27
3  Neptune      24633     14

In [25]:
df3 = df3.reset_index(drop=True)
df3

planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
4  Jupiter      69911     80
5   Saturn      58232     83
6   Uranus      25362     27
7  Neptune      24633     14

#### `merge()`:
A pandas function that joins two dataframes together; it only combines data by extending along axis one horizontally 

**Keys:**
- The shared points of reference between different dataframes - what to match on 

In [27]:
inner = pd.merge(df3, df2, on='planet', how='inner')
inner

planet  radius_km_x  moons_x  radius_km_y  moons_y
0  Jupiter        69911       80        69911       80
1   Saturn        58232       83        58232       83
2   Uranus        25362       27        25362       27
3  Neptune        24633       14        24633       14

In [29]:
outer = pd.merge(df3, df2, on='planet', how='outer')
outer

planet  radius_km_x  moons_x  radius_km_y  moons_y
0    Earth         6371        1          NaN      NaN
1  Jupiter        69911       80      69911.0     80.0
2     Mars         3390        2          NaN      NaN
3  Mercury         2440        0          NaN      NaN
4  Neptune        24633       14      24633.0     14.0
5   Saturn        58232       83      58232.0     83.0
6   Uranus        25362       27      25362.0     27.0
7    Venus         6052        0          NaN      NaN

In [30]:
left = pd.merge(df3, df2, on='planet', how='left')
left

planet  radius_km_x  moons_x  radius_km_y  moons_y
0  Mercury         2440        0          NaN      NaN
1    Venus         6052        0          NaN      NaN
2    Earth         6371        1          NaN      NaN
3     Mars         3390        2          NaN      NaN
4  Jupiter        69911       80      69911.0     80.0
5   Saturn        58232       83      58232.0     83.0
6   Uranus        25362       27      25362.0     27.0
7  Neptune        24633       14      24633.0     14.0

In [32]:
right = pd.merge(df3, df2, on='planet', how='right')
right


planet  radius_km_x  moons_x  radius_km_y  moons_y
0  Jupiter        69911       80        69911       80
1   Saturn        58232       83        58232       83
2   Uranus        25362       27        25362       27
3  Neptune        24633       14        24633       14